---
- name: deploy paython app on host server
  hosts: web
  #become: yes
  tasks:
    - name: Clone project code.
      copy:
        src: /home/ansadmin/copy-code/
        dest: /home/ansadmin/copy-code/
