---
- name: deploy paython app on host server
  hosts: web
  #become: yes
  tasks:
    - name: Clone project code.
      copy:
        src: /home/ansadmin/app.py
        dest: /home/ansadmin/copy-code/
    - name: Clone project code.
      copy:
        src: /home/ansadmin/requirements.txt
        dest: /home/ansadmin/copy-code/
